### ISSUE TITLE
Purchasing from opened presentation

### ISSUE THREAD

**Issue by tedlythgoe** [Purchasely/Purchasely-iOS#17]
We are looking to allow users to Purchase from a presentation opened over the top of an originally presented PLYPresentationViewController.

In the console we have done the following:
- Added an action of type "Open presentation"
- Selected another of our paywalls.

After making a purchase from the opened presentation, the view controllers are not dismissed causing a confusing user experience and meaning that users have to do this manually.

We've tried the following to dismiss the view controllers ourselves without any luck:

- Using the closure of the underlying controller called by the `presentationController` method but it is not called on purchase.
- Using the action interceptor but this only gives button taps rather than actual purchase events.
- Using the purchase notification through notification center but the notification is not received.

How do you suggest we handle this use case?

Thanks!

**Comment by EPIKorial** [comment]
Hello @tedlythgoe,

Thank you for getting in touch with us regarding this matter.

The behavior you're attempting to achieve is the expected functionality from our SDK. It should close the view controllers after a successful purchase.

Upon investigation, I regret to inform you that I haven't been able to reproduce the issue. 

- Could you please provide more details about your navigation stack? How do you open the `presentationController`? Is it presented modally or pushed onto a navigation stack? 
- The same question applies to the parent view of this `presentationController`.
- Additionally, could you confirm the version (4.1.4?) and mode (full or observer?) of the SDK you are using?
-  It would be helpful if you could share the identifier of the paywall where you are encountering this issue. 
- Are you experiencing this problem on a real device?

If possible, please provide the logs of a session where you are facing this problem. Your cooperation is greatly appreciated.

Thank you in advance for your responses.

Best regards,

Florian

**Comment by tedlythgoe** [comment]
Hi @EPIKorial,

Thanks for looking into this!

- The top-most `presentationController` is presented via the default behaviour from the "Open presentation" action specified in your console, which is modally. The parent `presentationController` is presented modally by our application.

- This has happened with every paywall we've tried but as an example, paywall id of the parent presentation controller is  `two-tier-v4` and the child is `single-payment-standard-v2` or `single-payment-premium-v2`

- We are using v4.1.0 of the SDK and full mode.

- I have only been using a real device to test this flow.

I will send over a video by email to our account manager.

Cheers,
Ted
