### ISSUE TITLE
Example project is out of date

### ISSUE THREAD

**Issue by saldous** [Purchasely/Purchasely-iOS#31]
Hi, your example project doesn't work and needs updating.

e.g. 
`Purchasely.isReadyToPurchase(true)`
Type 'Purchasely' has no member 'isReadyToPurchase'

I believe this needs changing to:
`Purchasely.readyToOpenDeeplink(true)`

and:
```
Purchasely.start(withAPIKey: "afa96c76-1d8e-4e3c-a48f-204a3cd93a15",
						 appUserId: "DEMO_USER",
                                                   logLevel: .debug)
```

needs changing to: (it was missing the now required storeKitSetting)
```
Purchasely.start(withAPIKey: "afa96c76-1d8e-4e3c-a48f-204a3cd93a15",
						 appUserId: "DEMO_USER",
                                                   storekitSettings: .storeKit2, 
                                                   logLevel: .debug)
```

and:
`Purchasely.handle(deeplink: url)`

needs changing to:
`Purchasely.isDeeplinkHandled(deeplink: url)`

It would also be good if you can add an example of how to handle restores.

**Comment by EPIKorial** [comment]
Hello @saldous, thank you so much for bringing this to our attention. You are absolutely right.

We are going to update this but also we are going to release a new version of this sample application really soon.

Best regards
