### ISSUE TITLE
Error installing Purchasely: Remote branch 4.3.6 not found in upstream origin

### ISSUE THREAD

**Issue by saldous** [Purchasely/Purchasely-iOS#40]
Just tried a 'pod update' and getting this error:

```
[!] Error installing Purchasely
[!] /usr/bin/git clone https://github.com/Purchasely/Purchasely-iOS.git /var/folders/4c/tg51wkw12vl20wwz9jwwwqs40000gn/T/d20240509-59170-ymozrw --template= --single-branch --depth 1 --branch 4.3.6

Cloning into '/var/folders/4c/tg51wkw12vl20wwz9jwwwqs40000gn/T/d20240509-59170-ymozrw'...
warning: Could not find remote branch 4.3.6 to clone.
fatal: Remote branch 4.3.6 not found in upstream origin
```

I see 4.3.4 here on GitHub, so why is cocoapods trying to pull 4.3.6?

My podfile has the below, no version specified: 
`pod 'Purchasely'`

**Comment by EPIKorial** [comment]
Hello @saldous ,

I'm Florian, and thank you for reaching out to us.

We regret to inform you that there was an issue with version 4.3.6 of our SDK. While we have implemented some changes to rectify the situation, it appears that we may have overlooked a crucial step which has led to the problem you are currently experiencing. 

Please accept our sincerest apologies for any inconvenience caused. We are actively working on resolving this issue and expect to have it rectified shortly.

Thank you for your patience and understanding.

Best regards,

Florian

**Comment by EPIKorial** [comment]
The `4.3.7` version of our SDK is now live and should solve your issue.

Using:
`pod 'Purchasely'`

Should work just fine. Consider using `pod install --repo-update` to make sure _cocoapod_ is pulling the last version of our SDK.

Once again, thank you for bringing this to our attention.

Best regards,
Florian
